### ISSUE TITLE
"index files are missing" error when running test command

### ISSUE THREAD

**Issue by robinengler** [dcouvin/CRISPRCasFinder#23]
Hi,
I'm trying to run the command to test my local install of `CRISPRCasFinder.pl`.  

`perl CRISPRCasFinder.pl -in install_test/sequence.fasta -cas -cf CasFinder-2.0.3 -def G -keep -soFile $VMATCH_SEL392`

but `macsyfinder` is telling me that it can't find some of the index files it needs (see error message below).  

I read through the documentation to see if there is an option to tell CRISPRCasFinder to build these index files, but didn't see anything. Or maybe I got something wrong in my `macsyfinder` installation.

Would you have any idea of what I'm not doing correctly?
Thanks in advance for any help.

```
...
...

prodigal installation is.............OK 
macsyfinder installation is...........OK 
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...526169 bp seq created, 52.76 pct GC
Locating all potential starts and stops...27714 nodes
Looking for GC bias in different frames...frame bias scores: 1.12 0.26 1.63
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (526169 bp)...done!
Traceback (most recent call last):
  File "/software/UHTS/Analysis/macsyfinder/1.0.5/bin/macsyfinder", line 329, in <module>
    idx.build(force = config.build_indexes)
  File "/software/UHTS/Analysis/macsyfinder/1.0.5/lib/python2.7/site-packages/macsypy/database.py", line 119, in build
    self._hmmer_indexes = self.find_hmmer_indexes()
  File "/software/UHTS/Analysis/macsyfinder/1.0.5/lib/python2.7/site-packages/macsypy/database.py", line 142, in find_hmmer_indexes
    raise RuntimeError(msg)
RuntimeError: some index files are missing. Delete all index files (*.phr, *.pin, *.psd, *.psi, *.psq, *.pal) and try to rebuild them.
No Cas results
Nb of Cas in this sequence = 0
Secondary folders/files (Prodigal, CasFinder, rawFASTA, CRISPRFinderProperties) have been created

All CRISPRs = 9
All Cas = 0

[14:55:46] Thank you for using CRISPRCasFinder.pl! Thank you for your patience!

[14:55:46] The script lasted: 0 year(s) 0 month(s) 0 day(s) , 0 hour(s) 0 minute(s) 4 second(s)
```

**Comment by dcouvin** [comment]
Hi @robinengler ,
Thank you for your message. Unfortunately, I have not seen this error yet.
Please try to re-install MacSyFinder following these instructions : https://macsyfinder.readthedocs.io/en/latest/installation.html
I hope this could help.
Maybe @bneron could provide further help.
Best regards,
@dcouvin

**Comment by ftianRF** [comment]
It is due to the incompatibility of macsyfinder with BLAST+ 2.10.0.
https://githubhot.com/repo/gem-pasteur/macsyfinder/issues/30
